### ISSUE TITLE
docker compose

### ISSUE THREAD

**Issue by leuchtrakete666** [guniv/CoolerControl-Docker#9]
hi,

thanks for this container! i love it. i am running a headless ai/gaming server with an asus proart x870e motherboard. for this i wrote the `compose.yml`:

```
services:
  coolercontroler:
    image: ghcr.io/guniv/coolercontrol-docker
    #privileged: true
    container_name: coolercontroler
    volumes:
      - ./config:/etc/coolercontroler
      - /sys/class/hwmon:/sys/class/hwmon:ro
      - /sys/class/hwmon/hwmon8:/sys/class/hwmon/hwmon8
    devices:
      - /dev/hidraw0
    ports:
      - "11987:11987"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
```

for the fans to be detected i needed to load the module `nct6775`. for testing with `sudo modprobe nct6775` and after confirming it worked i made it permanent by adding `nct6775.conf` with the line `nct6775` to `/etc/modules-load.d/`. for the rest i followed your guide, just adapting it to docker compose.
to find the right module for my motherboard i was googeling for fan control on linux with my asus proart. 
to make the fans writable it was not working with mapping the `/sys/devices/platform/nct6775.656` i had to map `/sys/class/hwmon/hwmon8`
